### ISSUE TITLE
about lmdb 

### ISSUE THREAD

**Issue by EraProphet** [researchmm/Stark#1]
hi, I Haven't used lmdb to read datasets before, could you tell me how to generate lmdb files? thanks

**Comment by MasterBin-IIAU** [comment]
Hi, it is not necessary to use the lmdb format. you can set "--use_lmdb 0" to disable the lmdb. 
But if you does have the requirement about the lmdb, we can provide a tutorial for it later.

**Comment by EraProphet** [comment]
thanks for your replying, but when I set "--use_lmdb 0", I got a ValueError: NOW WE CAN ONLY USE TRACKINGNET FROM LMDB.

**Comment by MasterBin-IIAU** [comment]
Hi, thanks for your notice. It is a small bug. And I guess it has been fixed now :)
Please update your local code by "git pull".
Could you help us to check whether the code can be run smoothly?

**Comment by EraProphet** [comment]
Thank you very much for fixing this bug, the program can run smoothly, and this is indeed  excellent work that can be learned a lot from it.

**Comment by EraProphet** [comment]
Thank you very much for fixing this bug, and the program can run smoothly.
