### ISSUE TITLE
Effect of template choice on transformer

### ISSUE THREAD

**Issue by waterknows** [researchmm/Stark#10]
Thanks for sharing! I have some questions around the choice of template. From the paper you cropped 2^2 times the ground truth bounding box, rather than just the actual target bounding box resized to square image. My questions are: 
1) Is the purpose here to include more surrounding information? If so what would be the optimal template size here? Also a factor of 2 would not always include the whole tracking object if aspect ratio is high.
2) By not specifying the bounding box exactly I assume the transformer has to learn some segmentation capability? For instance right now I noticed that if you change the template crop size (output size stay the same) a little bit during the inference time, the model would give very poor performance. So it seems that some information sensitive to absolute positions are learned in this setting. Would passing the exact coordinates into the transformer help in any way?

**Comment by MasterBin-IIAU** [comment]
Hi, thanks for your questions. Your thinking is quite deep :)
1. "Including some context information" is inspired by the SiamFC. We actually have tried removing the background information, but the performance dropped. So we keep this design. You are right about the extreme cases where the aspect ratio is too large or too small. Maybe there is still space in the template size design.
2. Yep. The network implicitly learns to locate or "segment" the target on the template image.  Besides, we also found that the learned models are quite sensitive to the "region cropping strategy" (how to crop the template and search region). If the training and testing use different strategies, the performance will drop drastically. I think this is also a potential direction for improvement.

**Comment by waterknows** [comment]
Got it. Thank you!
