### ISSUE TITLE
Some confusion about the speed.

### ISSUE THREAD

**Issue by lingqing97** [researchmm/Stark#11]
I want to know that do you test the speed on  a Tesla V100 GPU?
![image](https://user-images.githubusercontent.com/41864244/120915103-78fac980-c6d4-11eb-9fc5-9ba8b476a67a.png)

**Comment by MasterBin-IIAU** [comment]
Yes, the speed is tested on a Tesla V100 GPU.

**Comment by lingqing97** [comment]
ok,thanks!
