### ISSUE TITLE
A problem about loading checkpoint

### ISSUE THREAD

**Issue by 1071189147** [researchmm/Stark#16]
When I train ‘st’ model，I found  the 'net_type' is  ''**STARKS**'',but the checkpoint_dict['net_type'] is '**'LittleBoy_clean_corner**'',
so
`assert net_type == checkpoint_dict['net_type'], 'Network is not of correct type.'`It's always wrong.
![image](https://user-images.githubusercontent.com/28439235/125045018-23e51580-e0cf-11eb-860d-db8922d83d53.png)

How can I solve this problem?Thanks！

**Comment by MasterBin-IIAU** [comment]
Hi, please check whether you are using the latest code. "LittleBoy" is the name we previously use. Now this name should not occur in the latest code. You can update the code by "git pull". 
After updating the code, this problem should be fixed. 
If this problem still exists, please let me know.

**Comment by 1071189147** [comment]
> Hi, please check whether you are using the latest code. "LittleBoy" is the name we previously use. Now this name should not occur in the latest code. You can update the code by "git pull".
> After updating the code, this problem should be fixed.
> If this problem still exists, please let me know.

I'm using the latest code，‘’LittleBoy‘’ occurs in the  model of [https://drive.google.com/drive/folders/1144cEuF_yn9UwTfrSVl5wmaMK3F92q42](url)
It doesn't occured  in the code,Is there a problem with the model in the Model Zoo?

**Comment by MasterBin-IIAU** [comment]
a@1071189147 Hi, if you are fine-tuning the stark_st (spatio-temporal) model, you should not use the stark_s (spatial-only) checkpoints. The correct checkpoints should be https://drive.google.com/drive/folders/1fSgll53ZnVKeUn22W37Nijk-b9LGhMdN. Besides, the easiest way to solve the type problem is to comment out this line of "assert".

**Comment by 1071189147** [comment]
> a@1071189147 Hi, if you are fine-tuning the stark_st (spatio-temporal) model, you should not use the stark_s (spatial-only) checkpoints. The correct checkpoints should be https://drive.google.com/drive/folders/1fSgll53ZnVKeUn22W37Nijk-b9LGhMdN. Besides, the easiest way to solve the type problem is to comment out this line of "assert".

已经通过您所说的方法解决了问题，如果我现在想微调stark_st，请问我是否可以使用Model ZOO 中st2阶段的checkpoint, 先进行ST1 阶段的训练，再进行ST2 阶段的训练。

**Comment by MasterBin-IIAU** [comment]
Hi, yep you can :)

在 2021-07-09 20:23:16，mumumu ***@***.***> 写道：

***@***.*** Hi, if you are fine-tuning the stark_st (spatio-temporal) model, you should not use the stark_s (spatial-only) checkpoints. The correct checkpoints should be https://drive.google.com/drive/folders/1fSgll53ZnVKeUn22W37Nijk-b9LGhMdN. Besides, the easiest way to solve the type problem is to comment out this line of "assert".
