### ISSUE TITLE
where is the definition of a parameter of your codes

### ISSUE THREAD

**Issue by ANdong-star** [researchmm/Stark#17]
Hi, thanks for your work! There is a parameter making me confused. I don't find the definition of params in class STARK_ST and could you please tell me? Thanks!

![WY(8T DNSSX YPNIIT 6UE7](https://user-images.githubusercontent.com/51860191/125094153-9a046f00-e105-11eb-942f-08506c0ab2aa.png)

**Comment by MasterBin-IIAU** [comment]
@ANdong-star Hi, the params is obtained from [here](https://github.com/researchmm/Stark/blob/main/lib/test/parameter/stark_st.py).

**Comment by ANdong-star** [comment]
> @ANdong-star Hi, the params is obtained from [here](https://github.com/researchmm/Stark/blob/main/lib/test/parameter/stark_st.py).

Yep,  I find it! Thanks!
