### ISSUE TITLE
train on 4 11GB RTX 2080Ti gpus

### ISSUE THREAD

**Issue by ANdong-star** [researchmm/Stark#18]
Hi! Is it possible to train Stark on  4 11GB RTX 2080Ti gpus?

**Comment by MasterBin-IIAU** [comment]
@ANdong-star Hi, yep, you can achieve this by just replacing the "--nproc_per_node 8" with "--nproc_per_node 4".

**Comment by ANdong-star** [comment]
> @ANdong-star Hi, yep, you can achieve this by just replacing the "--nproc_per_node 8" with "--nproc_per_node 4".

ok, thanks very much!
