### ISSUE TITLE
Raw results

### ISSUE THREAD

**Issue by 2006pmach** [researchmm/Stark#2]
Hi, thanks for sharing the work. I saw that in the model zoo readme file you are mentioning raw results but I couldn't find a link referring to them. Could you give me a hand? Thanks in advance.

**Comment by MasterBin-IIAU** [comment]
Hi, thanks for your kind reminding :) 
Now the link for the raw results has been updated. 
You can check it in the MODEL_ZOO.md 
Please let me know if you can access the raw results normally. Thanks :)

**Comment by MasterBin-IIAU** [comment]
Hi, I guess the problem has gone. Let's close this issue now :)
