### ISSUE TITLE
how long did the training take?

### ISSUE THREAD

**Issue by ANdong-star** [researchmm/Stark#20]
Hi! How long did the traning take using 8 16gb V100? I use 4 11gb 2080ti to train the model for 500 epoch and it will take 20 days.

**Comment by MasterBin-IIAU** [comment]
It only takes about 2 days to train STARK with 8 16GB V100 GPUs.

**Comment by ANdong-star** [comment]
> It only takes about 2 days to train STARK with 8 16GB V100 GPUs.

really fast, thanks.
