### ISSUE TITLE
the meaning of  "lmdb" in "self.lasot_lmdb_dir"

### ISSUE THREAD

**Issue by ANdong-star** [researchmm/Stark#21]
Hi! Could you please tell what is the meaning of "lmdb" in class EnvironmentSettings "self.lasot_lmdb_dir"? I guess it is the dir of val dataset of lasot?

**Comment by MasterBin-IIAU** [comment]
No. "lmdb_dir" is only valid when you prepare your datasets into lmdb format.

**Comment by ANdong-star** [comment]
> No. "lmdb_dir" is only valid when you prepare your datasets into lmdb format.

ok,thanks.
