### ISSUE TITLE
thansk for your amazing work, how to test on my video in your model?

### ISSUE THREAD

**Issue by codylcs** [researchmm/Stark#22]

**Comment by MasterBin-IIAU** [comment]
@codylcs Hi, you can use [tracking/video_demo.py](https://github.com/researchmm/Stark/blob/main/tracking/video_demo.py) by the following command
```python tracking/video_demo.py stark_s baseline <path_of_your_video_file>```

**Comment by codylcs** [comment]
> @codylcs Hi, you can use [tracking/video_demo.py](https://github.com/researchmm/Stark/blob/main/tracking/video_demo.py) by the following command
> `python tracking/video_demo.py stark_s baseline <path_of_your_video_file>`

thanks,demo has been run,however,when use internet video to test,u will see the track box will from one man to another suddenly,any advices?

**Comment by MasterBin-IIAU** [comment]
@codylcs Hi, the sudden drift is partially caused by the lack of temporal-smoothness post-processing (such as cosine window, etc). We also find that STARK performs well in dealing with target disappearance and reappearance (especially important for long-term tracking), while struggles dealing similar distractors. So I think it could be a promising direction to improve the ability of STARK to deal with distractors.

**Comment by codylcs** [comment]
thanks for your answer,  good luck

**Comment by nomurakeiya** [comment]
@MasterBin-IIAU 

It's closed, but let me ask you a question!
If I give video_demo.py the path of the video, can I get the tracking result for that video?

I want to try tracking on unknown videos, not testing or training.

Currently when I run it I get the following error:


> C:\Users\USER\mysystem\detection\Stark>python tracking/video_demo.py stark_st2 baseline xxx.mp4
> Traceback (most recent call last):
>   File "C:\Users\USER\mysystem\detection\Stark\lib\test\evaluation\environment.py", line 111, in env_settings
>     env_module = importlib.import_module(env_module_name)
>   File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 779, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 916, in get_code
>   File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "C:\Users\USER\mysystem\detection\Stark\lib\test\evaluation\local.py", line 9
>     settings.got10k_lmdb_path = 'C:\Users\USER\mysystem\detection\Stark\data\got10k_lmdb'
>                                 ^
> SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "tracking/video_demo.py", line 39, in <module>
>     main()
>   File "tracking/video_demo.py", line 35, in main
>     run_video(args.tracker_name, args.tracker_param, args.videofile, args.optional_box, args.debug, args.save_results)
>   File "tracking/video_demo.py", line 19, in run_video
>     tracker = Tracker(tracker_name, tracker_param, "video")
>   File "C:\Users\USER\mysystem\detection\Stark\lib\test\evaluation\tracker.py", line 46, in __init__
>     env = env_settings()
>   File "C:\Users\USER\mysystem\detection\Stark\lib\test\evaluation\environment.py", line 118, in env_settings
>     raise RuntimeError('YOU HAVE NOT SETUP YOUR local.py!!!\n Go to "{}" and set all the paths you need. '
> RuntimeError: YOU HAVE NOT SETUP YOUR local.py!!!
>  Go to "C:\Users\USER\mysystem\detection\Stark\lib\test\evaluation\local.py" and set all the paths you need. Then try to run again.
