### ISSUE TITLE
how to analysis the model on GOT10k-val dataset?

### ISSUE THREAD

**Issue by 3bobo** [researchmm/Stark#25]
Thanks for your work! I trained the model and want to evaluate it on the GOT10k-Val dataset to see its performance, but only see 'LaSOT', 'otb', 'nfs', 'uav', 'tc128ce' datasets, so how to evaluate on the GOT10k-Val? By the way, what's the difference between `analysis_results` and `analysis_results_ITP` files?

**Comment by MasterBin-IIAU** [comment]
Hi, actually we haven't evaluate our method on GOT-10K before, so I am not quite sure if the code supports that. 
However, after getting the original tracking results with this project,  you can evaluate it with the official [got10k toolkit](https://github.com/got-10k/toolkit).

**Comment by MasterBin-IIAU** [comment]
About the different script names, there are actually no difference in functions, so you can just overlook them :)

**Comment by 3bobo** [comment]
Ok, thanks for your reply!
