### ISSUE TITLE
Run video_demo.py

### ISSUE THREAD

**Issue by Nick-Sun1018** [researchmm/Stark#27]
Thanks for your excellent work, could you please show me how to run video_demo.py with pretrained model, thanks a lot!

**Comment by ayanasser** [comment]
I need this too, thank you ^^

**Comment by ayanasser** [comment]
The solution of this issue is here: 
https://github.com/researchmm/Stark/issues/22

**Comment by MasterBin-IIAU** [comment]
@ayanasser Thanks :)
