### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by Omri-L** [researchmm/Stark#3]
Hi,
Which license this repository uses?

Thanks,
Omri.

**Comment by MasterBin-IIAU** [comment]
Hi, sorry for the late reply. This repo adopts MIT LICNESE. 
We have just added MIT LICENSE to the repository.

**Comment by Omri-L** [comment]
> Hi, sorry for the late reply. This repo adopts MIT LICNESE.
> We have just added MIT LICENSE to the repository.

Great, Thanks :)
