### ISSUE TITLE
 Alpha-Refine  Problems

### ISSUE THREAD

**Issue by fz-gl** [researchmm/Stark#4]
您好！您上传的包有问题，无法解压！
https://drive.google.com/file/d/1qOQRfaRMbQ2nmgX1NFjoQHfXOAn609QM/view

**Comment by MasterBin-IIAU** [comment]
Hi, there is no need of unzipping. Pytorch can directly load checkpoints of .pth format.

**Comment by fz-gl** [comment]
when we download, we would get .tar file not . pt or . pth



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 23, 2021 17:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [researchmm/Stark]  Alpha-Refine  Problems (#4)




 
Hi, there is no need of unzipping. Pytorch can directly load checkpoints of .pth format.

**Comment by MasterBin-IIAU** [comment]
As I said, please directly use the .pth.tar file rather than unzipping it

**Comment by fz-gl** [comment]
thanks



---Original---
From: ***@***.***&gt;
Date: Fri, Apr 23, 2021 20:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [researchmm/Stark]  Alpha-Refine  Problems (#4)




 
As I said, please directly use the .pth.tar file rather than unzipping it
