### ISSUE TITLE
torchvision version detection

### ISSUE THREAD

**Issue by MamoruDS** [researchmm/Stark#42]
Hello, I noticed some problems with the implementation of the code that detects the version of `torchvision` in `utils.misc.py`

```python
import torchvision
if float(torchvision.__version__[:3]) < 0.7:
    from torchvision.ops import _new_empty_tensor
    from torchvision.ops.misc import _output_size
```
This will have a fatal issue for `torchvision>=0.10`

```shell
python -c "import torchvision; print(torchvision.__version__[:3])"
# output equals 0.1
```

**Comment by MasterBin-IIAU** [comment]
@MamoruDS Hi, thanks for pointing out this bug. This problem has been fixed.
