### ISSUE TITLE
Training speed

### ISSUE THREAD

**Issue by JingweiZhang12** [researchmm/Stark#58]
Hi, thanks for your work!
Training stark on our machine also consumes too long time, about 5~6 days. Could you please provide your data IO time and forward/backward time in your training process as my reference?

**Comment by wjh-scut** [comment]
> Hi, thanks for your work! Training stark on our machine also consumes too long time, about 5~6 days. Could you please provide your data IO time and forward/backward time in your training process as my reference?

请问您解决这个问题了吗？
