### ISSUE TITLE
Do you try to use the full resnet?

### ISSUE THREAD

**Issue by LeungWaiHo** [researchmm/Stark#62]
Dear authors:
Do you try to use the full resnet as the backbone? And how is its performance? Drop or similar?
Thanks!

**Comment by MasterBin-IIAU** [comment]
@LeungWaiHo Hi, we have tried use the last stage (both stage5 and dilated stage5) of the resnet backbone, the performance is slightly lower than using stage4 (stride=16). Besides, considering the large computational cost and number of parameters brought by stage5, we finally choose to use the stage4.

**Comment by LeungWaiHo** [comment]
> @LeungWaiHo Hi, we have tried use the last stage (both stage5 and dilated stage5) of the resnet backbone, the performance is slightly lower than using stage4 (stride=16). Besides, considering the large computational cost and number of parameters brought by stage5, we finally choose to use the stage4.

Thanks for your answer via email & github again!!!
