### ISSUE TITLE
stark_light中decoder的问题

### ISSUE THREAD

**Issue by alistlhks** [researchmm/Stark#64]
作者你好，我在看你在极市平台直播中讲了stark_light的部分，我有个问题，在stark_s的基础上去掉decoder只降低了0.2%的表现，但是论文中所展示的stark_st去掉decoder之后却下降了1.9%，比去掉decoder的stark_s的表现还要低一些，这是为什么呢？因为加入额外的样本，单独的encoder无法准确学习吗，如果加入更多的encoder，再去掉decoder会怎么样呢？

**Comment by MasterBin-IIAU** [comment]
Hi, for stark-s, the decoder only provides a spatial-attention in the box prediction head. But in stark-st, the decoder is also used to predict the tracking score! If the tracking score is inaccurate, the noisy dynamic template may hurt the tracking performance. That is why the importance of decoder is different for stark-s and stark-st
