### ISSUE TITLE
Dataloader will randomly crashed

### ISSUE THREAD

**Issue by memoiry** [researchmm/Stark#7]
Hi.

I found that the training process will randomly crashed with `RuntimeError: DataLoader worker (pid(s) 36469) exited unexpectedly`, is that normal? 

I use the following training command.
```
python tracking/train.py --script stark_s --config baseline_got10k_only --save_dir . --mode multiple --nproc_per_node 8
```

thanks!

**Comment by MasterBin-IIAU** [comment]
Hi, we don't see similar problems. 
Perhaps it is caused by problems in your local dataset.

**Comment by memoiry** [comment]
Hi @MasterBin-IIAU , thanks for your reply.

I found that I have to manually set `'got10k_dir': os.path.join(data_dir, 'got10k', 'train'),` instead of `'got10k_dir': os.path.join(data_dir, 'got10k'),` in the environment code to make the code working, is that normal?

Thanks!

**Comment by memoiry** [comment]
It seems the problem is caused by me docker memory limitation. I tried to increase it and the problem is solved. 

Thanks!

**Comment by MasterBin-IIAU** [comment]
> It seems the problem is caused by the memory limitation of my docker env. I tried to increase it and the problem is solved.

Good :) Congratulation on solving the problem.

**Comment by memoiry** [comment]
Got it, thanks!

**Comment by MaiAbboud** [comment]
Hello 
what do you mean by docker env ?
