### ISSUE TITLE
How long is STARK-S50 model training?

### ISSUE THREAD

**Issue by Soarkey** [researchmm/Stark#75]
Hi, I want to use 4 GTX-1080Ti cards to train the STARK-S50.
Before that, I would like to ask the approximate training time of the model.
Thanks!

**Comment by JingweiZhang12** [comment]
We re-implement the STARK method on [mmtracking.](https://github.com/open-mmlab/mmtracking) We spend about two days training the 1st stage stark model and about 4 hours training the 2nd stage stark model.

**Comment by Soarkey** [comment]
I will check this project later.
Thanks for your help!
