### ISSUE TITLE
why not set sequential input of the data

### ISSUE THREAD

**Issue by ANdong-star** [researchmm/Stark#9]
Hi, thanks for your work. I find from your codes that "shuffle = True" when setting dataloaders. So if the input data is not sequential, how to update template every 200 frames? thanks!

**Comment by MasterBin-IIAU** [comment]
Hi, sorry I don't quite understand your question. Could you refer to a detailed line of code?
"shuffle=True" is about the training, while "update the dynamic template every 200 frames" is about the test.

**Comment by ANdong-star** [comment]
> Hi, sorry I don't quite understand your question. Could you refer to a detailed line of code?
> "shuffle=True" is about the training, while "update the dynamic template every 200 frames" is about the test.

Thanks! Now I understand it！
